// File: client/src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    nav: {
      home: 'Home',
      directory: 'Directory',
      resources: 'Resources',
      about: 'About',
      partners: 'Partners',
      adminLogin: 'Admin Login',
      language: 'Language',
      switchToSpanish: 'Switch to Spanish',
      switchToEnglish: 'Switch to English',
    },
    dashboard: {
      layout: {
        adminLabel: 'Admin',
        dashboardTitle: 'Dashboard',
        dashboardSection: 'Dashboard',
        mainSiteSection: 'Main Site',
        websiteThemeSection: 'Website Theme',
        logout: 'Logout',
      },
      sidebar: {
        dashboardLabel: 'Dashboard',
        contentCms: 'Content CMS',
        expandSidebar: 'Expand sidebar',
        collapseSidebar: 'Collapse sidebar',
      },
      links: {
        homeEditor: 'Home Editor',
        resourcesEditor: 'Resources Editor',
        aboutEditor: 'About Editor',
        partnersEditor: 'Partners Editor',
        directoryEditor: 'Directory Editor',
        websiteThemeEditor: 'Website Theme',
        themeColorsEditor: 'Theme Colors',
      },
      common: {
        status: 'Status',
        loadingContent: 'Loading content...',
        savingChanges: 'Saving changes...',
        allChangesSaved: 'All changes saved',
        actionNeeded: 'Action needed',
        unsavedChanges: 'Unsaved changes',
        noPendingChanges: 'No pending changes',
        lastSaved: 'Last saved:',
        saving: 'Saving...',
        saveChanges: 'Save changes',
        undoChanges: 'Undo changes',
        loggedInAs: 'Logged in as',
        adminFallback: 'Admin',
        delete: 'Delete',
        add: 'Add',
        pageCopy: 'Page copy',
        pageTitle: 'Page title',
        pageSubtitle: 'Page subtitle',
        showing: 'Showing',
        of: 'of',
        changesReverted: 'Changes reverted.',
        fillRequiredBeforeSave: 'Please fill in all required fields before saving.',
      },
      home: {
        pill: 'Home Page',
        title: 'Edit home page content',
        description: 'Update the hero section text and image used on the public homepage.',
        loadingMessage: 'Loading home page content...',
        loadError: 'Unable to load home page content. Using defaults instead.',
        heroTextTitle: 'Hero text',
        heroTextSubtitle: 'These fields appear at the top of the homepage.',
        heroTitleLabel: 'Hero title',
        heroDescriptionLabel: 'Hero description',
        ctaLabel: 'CTA button label',
        supportingPartnersLabel: 'Supporting partners label',
        heroImageTitle: 'Hero image',
        heroImageSubtitle: 'Paste a public image URL or leave it blank to use the default image.',
        imageUrlLabel: 'Image URL',
        imageAltLabel: 'Image description (alt text)',
        heroPreviewAlt: 'Hero preview',
        saveSuccess: 'Changes saved successfully.',
        saveError: 'Unable to save changes.',
      },
      about: {
        pill: 'About Page',
        title: 'Edit about content',
        description: 'Update the title and paragraph copy shown on the public about page.',
        loadingMessage: 'Loading about page content...',
        loadError: 'Unable to load about content. Using defaults instead.',
        paragraphLabel: 'Paragraph',
        newParagraph: 'New paragraph added.',
        removeConfirm: 'Remove this paragraph?',
        removeError: 'Keep at least one paragraph.',
        removed: 'Paragraph removed.',
        pageCopySubtitle: 'These fields appear on the about page.',
        saveSuccess: 'Changes saved successfully.',
        saveError: 'Unable to save changes.',
      },
      partners: {
        pill: 'Partners Page',
        title: 'Edit partners content',
        description: 'Update partner cards shown on the public partners page.',
        loadingMessage: 'Loading partners content...',
        loadError: 'Unable to load partners content. Using defaults instead.',
        newPartner: 'New partner added.',
        removeConfirm: 'Remove this partner?',
        removeError: 'Keep at least one partner.',
        removed: 'Partner removed.',
        cardsTitle: 'Partner cards',
        cardsSubtitle: 'Edit each partner card. English description is required.',
        searchLabel: 'Search partners',
        searchPlaceholder: 'Search by name, URL, or description',
        partnerLabel: 'Partner',
        nameLabel: 'Name',
        websiteLabel: 'Website URL',
        logoKeyLabel: 'Logo key (optional)',
        logoUrlLabel: 'Logo URL (optional)',
        logoUrlPlaceholder: 'https://example.com/logo.png',
        descriptionEn: 'Description (English)',
        descriptionEs: 'Description (Spanish)',
        invertLogo: 'Invert logo colors',
        addPartner: 'Add partner',
        noLogoKey: 'No logo key',
        saveSuccess: 'Changes saved successfully.',
        saveError: 'Unable to save changes.',
      },
      resources: {
        pill: 'Resources Page',
        title: 'Edit resources content',
        description: 'Update the title, subtitle, and resource cards shown on the public resources page.',
        loadingMessage: 'Loading resources page content...',
        loadError: 'Unable to load resources content. Using defaults instead.',
        newCard: 'New card added.',
        removeConfirm: 'Remove this resource card?',
        removeError: 'Keep at least one resource card.',
        removed: 'Resource card removed.',
        pageCopySubtitle: 'These fields appear at the top of the resources page.',
        cardsTitle: 'Resource cards',
        cardsSubtitle: 'Edit each card to match the public page.',
        cardLabel: 'Card',
        titleLabel: 'Title',
        descriptionLabel: 'Description',
        ctaLabel: 'CTA label',
        linkUrlLabel: 'Link URL',
        addCard: 'Add resource card',
        saveSuccess: 'Changes saved successfully.',
        saveError: 'Unable to save changes.',
      },
      directory: {
        pill: 'Directory Page',
        title: 'Edit directory services',
        description: 'Update services manually or upload an Excel/CSV file to replace the directory data.',
        loadingMessage: 'Loading directory services...',
        loadError: 'Unable to load directory services.',
        newService: 'New service added.',
        removeConfirm: 'Remove this service?',
        removeError: 'Keep at least one service.',
        removed: 'Service removed.',
        fillRequiredBeforeSave: 'Please fill in required fields before saving.',
        uploadTitle: 'Upload directory file',
        uploadSubtitle: 'Upload an Excel or CSV file to replace all directory entries.',
        exportCsv: 'Export CSV',
        chooseFile: 'Choose a file to upload',
        acceptedFiles: 'Accepted: .xlsx, .xls, .csv up to 5MB.',
        uploadFile: 'Upload file',
        uploading: 'Uploading...',
        preparingExport: 'Preparing export...',
        allSet: 'All set.',
        somethingWrong: 'Something went wrong.',
        uploadComplete: 'Upload complete. Imported',
        servicesLabel: 'services.',
        uploadFailed: 'Upload failed.',
        exportDownloaded: 'Export downloaded.',
        exportFailed: 'Export failed.',
        uploadMessage: 'Uploading file...',
        exportMessage: 'Preparing export...',
        entriesTitle: 'Service entries',
        entriesSubtitle: 'Provider name is required.',
        addService: 'Add service',
        searchLabel: 'Search services',
        searchPlaceholder: 'Search by provider, category, or county',
        serviceLabel: 'Service',
        providerName: 'Provider name',
        serviceCategory: 'Service category',
        serviceTypes: 'Service types',
        websiteUrl: 'Website URL',
        phone: 'Phone',
        serviceTimes: 'Service times',
        accessibility: 'Accessibility',
        cost: 'Cost',
        countiesServed: 'Counties served',
        saveSuccess: 'Changes saved successfully.',
        saveError: 'Unable to save changes.',
      },
      websiteTheme: {
        pill: 'Theme Colors',
        title: 'Customize theme colors',
        description: 'Phase 2 - Step 1: control global background, text, and primary color.',
        autoSaveTitle: 'Auto save enabled',
        autoSaveDescription: 'Use Save Changes to apply updates to the public website.',
        controlsTitle: 'Theme controls',
        controlsDescription: 'Use these color pickers to define your base website palette.',
        backgroundColor: 'Background color',
        textColor: 'Text color',
        primaryColor: 'Primary color',
        resetTheme: 'Reset to default',
        defaultsLoaded: 'Default theme loaded. Click Save Changes to apply it.',
        saveSuccess: 'Website theme saved successfully.',
        saveError: 'Unable to save website theme.',
        invalidHex: 'Please enter valid hex colors (example: #ffffff).',
        previewTitle: 'Live preview',
        previewDescription: 'This preview matches the public website theme variables.',
        previewHeading: 'Sample section',
        previewBody: 'Your website style updates immediately while you edit these values.',
        previewButton: 'Primary action',
      },
    },
    home: {
      heroTitle: 'CHOICE Regional Transportation Hub',
      heroDescription1: 'This is the CHOICE Regional Transportation Hub created to help connect community members and providers with transportation resources across the region.',
      heroDescription2: 'This hub was developed in response to regional needs identified through community input and collaboration to improve access to essential care services.',
      heroCta: 'Start My Search',
      heroImageAlt: 'Supportive driver providing transportation',
      partnerLogoAlt: 'Partner',
      supportingPartners: 'Supporting Partners',
      regionalTitleLine1: 'CHOICE Regional',
      regionalTitleLine2: 'Partners',
      regionalP1:
        'We believe that healthy communities are built on strong relationships, where people and community members are connected with one another and to essential services.',
      regionalP2:
        'We are dedicated to working together on community-driven solutions to solve some our most complex challenges in the central western Washington state region.',
      regionalP3:
        'This is a CHOICE regional transportation resource hub. CHOICE is working with local partners to help you get where you need to go.',
      regionalMapAlt: 'Washington State Map showing CHOICE Regional Partners',
      categories: {
        doctor: 'Rides to See a Doctor',
        groceries: 'Rides for Food & Groceries',
        work: 'Rides for Housing & Work',
        transit: 'Buses & Public Transit',
      },
      needHelpTitle: 'Need Extra Help?',
      needHelpCta: 'Start My Search',
      contactTitle: 'Do you have a suggested resource that we should know about? Let us know!',
      contactFirstName: 'First name',
      contactLastName: 'Last name',
      contactEmail: 'Email',
      contactFeedback: 'Feedback',
      contactSubmit: 'Submit',
      contactSubmitting: 'Submitting...',
      contactSuccessTitle: 'Thank You!',
      contactSuccessBody: "Your message has been sent successfully. We'll get back to you soon.",
      contactSendAnother: 'Send another message',
      validation: {
        firstNameMin: 'First name must be at least 2 characters.',
        lastNameMin: 'Last name must be at least 2 characters.',
        emailInvalid: 'Please enter a valid email address.',
        feedbackMin: 'Feedback must be at least 10 characters.',
      },
    },
    directory: {
      title: 'Find Transportation Services',
      filterTitle: 'Filter Services',
      searchByName: 'Search by name',
      allCounties: 'All Counties',
      searchCounties: 'Search counties',
      allServices: 'Type of Help',
      searchServices: 'Search type of help',
      allAccessibility: 'All Accessibility',
      searchAccessibility: 'Search accessibility',
      startSearch: 'Start My Search',
      clearAll: 'Clear All',
      noServicesTitle: 'No Services Found',
      noServicesBody: "We couldn't find any services matching your current filters. Try adjusting your search criteria.",
      clearFilters: 'Clear all filters',
      detail: {
        phone: 'Phone',
        hours: 'Hours',
        access: 'Access',
        cost: 'Cost',
        county: 'County',
      },
    },
    partners: {
      searchPlaceholder: 'Search partners...',
      showLess: 'Show less',
      readMore: 'Read more',
      website: 'Website',
      noResults: 'No results found',
    },
    about: {
      title: 'About & Partners',
      p1: 'The CHOICE Regional Transportation Hub was developed and is maintained by CHOICE Regional Health Network to improve access to transportation for community members across the region. CHOICE created this hub to make it easier for individuals, providers, and care coordinators to find and use transportation services that support access to medical care and essential needs.',
      p2: 'This work builds on regional collaboration through the Great Rivers BH-ASO Transportation Collaborative, where partners identified transportation as a major barrier to accessing care. Community surveys and partner feedback showed that many people were unaware of available transportation resources or unsure how to access them.',
      p3: 'In response, CHOICE Regional Health Network took the lead in creating this centralized hub to bring transportation information together in one place. This hub reflects CHOICE\'s ongoing commitment to improving access to care and strengthening connections between community members and essential services.',
      p4: 'Supporting partners in this effort include Great Rivers BH-ASO, UnitedHealthcare and the Cowlitz-Wahkiakum Council of Governments Mobility Management program, whose collaboration and input helped inform the development of this resource.',
    },
    resources: {
      title: 'Regional Transportation Resources',
      subtitle: 'Key tools and partners helping people access care, food, and essential services.',
      cwcogTitle: 'CWCOG Mobility Management',
      cwcogDesc: 'Mobility management tools, travel training, and regional coordination to connect people with transportation options.',
      cwcogCta: 'Visit CWCOG Mobility Management',
      grTitle: 'Great Rivers BH-ASO Transportation Efforts',
      grDesc: 'Regional coordination focused on improving access to transportation for behavioral health and other essential services.',
      grCta: 'Learn more about Great Rivers BH-ASO',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      directory: 'Directorio',
      resources: 'Recursos',
      about: 'Acerca de',
      partners: 'Socios',
      adminLogin: 'Acceso Admin',
      language: 'Idioma',
      switchToSpanish: 'Cambiar a español',
      switchToEnglish: 'Cambiar a inglés',
    },
    dashboard: {
      layout: {
        adminLabel: 'Admin',
        dashboardTitle: 'Panel',
        dashboardSection: 'Panel',
        mainSiteSection: 'Sitio principal',
        websiteThemeSection: 'Tema del sitio',
        logout: 'Cerrar sesión',
      },
      sidebar: {
        dashboardLabel: 'Panel',
        contentCms: 'CMS de contenido',
        expandSidebar: 'Expandir barra lateral',
        collapseSidebar: 'Contraer barra lateral',
      },
      links: {
        homeEditor: 'Editor de inicio',
        resourcesEditor: 'Editor de recursos',
        aboutEditor: 'Editor de acerca de',
        partnersEditor: 'Editor de socios',
        directoryEditor: 'Editor de directorio',
        websiteThemeEditor: 'Tema del sitio',
        themeColorsEditor: 'Colores del tema',
      },
      common: {
        status: 'Estado',
        loadingContent: 'Cargando contenido...',
        savingChanges: 'Guardando cambios...',
        allChangesSaved: 'Todos los cambios guardados',
        actionNeeded: 'Acción requerida',
        unsavedChanges: 'Cambios sin guardar',
        noPendingChanges: 'Sin cambios pendientes',
        lastSaved: 'Última actualización:',
        saving: 'Guardando...',
        saveChanges: 'Guardar cambios',
        undoChanges: 'Deshacer cambios',
        loggedInAs: 'Con sesión iniciada como',
        adminFallback: 'Admin',
        delete: 'Eliminar',
        add: 'Agregar',
        pageCopy: 'Contenido de la página',
        pageTitle: 'Título de la página',
        pageSubtitle: 'Subtítulo de la página',
        showing: 'Mostrando',
        of: 'de',
        changesReverted: 'Cambios revertidos.',
        fillRequiredBeforeSave: 'Completa todos los campos obligatorios antes de guardar.',
      },
      home: {
        pill: 'Página de inicio',
        title: 'Editar contenido de la página de inicio',
        description: 'Actualiza el texto e imagen del encabezado de la página pública.',
        loadingMessage: 'Cargando contenido de la página de inicio...',
        loadError: 'No se pudo cargar el contenido. Usando valores predeterminados.',
        heroTextTitle: 'Texto del encabezado',
        heroTextSubtitle: 'Estos campos aparecen en la parte superior de la página.',
        heroTitleLabel: 'Título del encabezado',
        heroDescriptionLabel: 'Descripción del encabezado',
        ctaLabel: 'Etiqueta del botón CTA',
        supportingPartnersLabel: 'Etiqueta de socios de apoyo',
        heroImageTitle: 'Imagen del encabezado',
        heroImageSubtitle: 'Pega una URL pública de imagen o déjala en blanco para usar la predeterminada.',
        imageUrlLabel: 'URL de la imagen',
        imageAltLabel: 'Descripción de la imagen (texto alternativo)',
        heroPreviewAlt: 'Vista previa del encabezado',
        saveSuccess: 'Cambios guardados correctamente.',
        saveError: 'No se pudieron guardar los cambios.',
      },
      about: {
        pill: 'Página acerca de',
        title: 'Editar contenido de acerca de',
        description: 'Actualiza el título y los párrafos que se muestran en la página pública.',
        loadingMessage: 'Cargando contenido de acerca de...',
        loadError: 'No se pudo cargar el contenido. Usando valores predeterminados.',
        paragraphLabel: 'Párrafo',
        newParagraph: 'Nuevo párrafo agregado.',
        removeConfirm: '¿Eliminar este párrafo?',
        removeError: 'Mantén al menos un párrafo.',
        removed: 'Párrafo eliminado.',
        pageCopySubtitle: 'Estos campos aparecen en la página acerca de.',
        saveSuccess: 'Cambios guardados correctamente.',
        saveError: 'No se pudieron guardar los cambios.',
      },
      partners: {
        pill: 'Página de socios',
        title: 'Editar contenido de socios',
        description: 'Actualiza las tarjetas de socios que se muestran en la página pública.',
        loadingMessage: 'Cargando contenido de socios...',
        loadError: 'No se pudo cargar el contenido. Usando valores predeterminados.',
        newPartner: 'Nuevo socio agregado.',
        removeConfirm: '¿Eliminar este socio?',
        removeError: 'Mantén al menos un socio.',
        removed: 'Socio eliminado.',
        cardsTitle: 'Tarjetas de socios',
        cardsSubtitle: 'Edita cada tarjeta. La descripción en inglés es obligatoria.',
        searchLabel: 'Buscar socios',
        searchPlaceholder: 'Buscar por nombre, URL o descripción',
        partnerLabel: 'Socio',
        nameLabel: 'Nombre',
        websiteLabel: 'URL del sitio web',
        logoKeyLabel: 'Clave del logo (opcional)',
        logoUrlLabel: 'URL del logo (opcional)',
        logoUrlPlaceholder: 'https://example.com/logo.png',
        descriptionEn: 'Descripción (inglés)',
        descriptionEs: 'Descripción (español)',
        invertLogo: 'Invertir colores del logo',
        addPartner: 'Agregar socio',
        noLogoKey: 'Sin clave de logo',
        saveSuccess: 'Cambios guardados correctamente.',
        saveError: 'No se pudieron guardar los cambios.',
      },
      resources: {
        pill: 'Página de recursos',
        title: 'Editar contenido de recursos',
        description: 'Actualiza el título, subtítulo y tarjetas mostradas en la página pública.',
        loadingMessage: 'Cargando contenido de recursos...',
        loadError: 'No se pudo cargar el contenido. Usando valores predeterminados.',
        newCard: 'Nueva tarjeta agregada.',
        removeConfirm: '¿Eliminar esta tarjeta de recurso?',
        removeError: 'Mantén al menos una tarjeta de recurso.',
        removed: 'Tarjeta de recurso eliminada.',
        pageCopySubtitle: 'Estos campos aparecen en la parte superior de la página.',
        cardsTitle: 'Tarjetas de recursos',
        cardsSubtitle: 'Edita cada tarjeta para que coincida con la página pública.',
        cardLabel: 'Tarjeta',
        titleLabel: 'Título',
        descriptionLabel: 'Descripción',
        ctaLabel: 'Etiqueta del CTA',
        linkUrlLabel: 'URL del enlace',
        addCard: 'Agregar tarjeta de recurso',
        saveSuccess: 'Cambios guardados correctamente.',
        saveError: 'No se pudieron guardar los cambios.',
      },
      directory: {
        pill: 'Página de directorio',
        title: 'Editar servicios del directorio',
        description: 'Actualiza servicios manualmente o sube un archivo Excel/CSV para reemplazar los datos.',
        loadingMessage: 'Cargando servicios del directorio...',
        loadError: 'No se pudieron cargar los servicios del directorio.',
        newService: 'Nuevo servicio agregado.',
        removeConfirm: '¿Eliminar este servicio?',
        removeError: 'Mantén al menos un servicio.',
        removed: 'Servicio eliminado.',
        fillRequiredBeforeSave: 'Completa los campos obligatorios antes de guardar.',
        uploadTitle: 'Subir archivo del directorio',
        uploadSubtitle: 'Sube un archivo Excel o CSV para reemplazar todas las entradas.',
        exportCsv: 'Exportar CSV',
        chooseFile: 'Elige un archivo para subir',
        acceptedFiles: 'Aceptado: .xlsx, .xls, .csv hasta 5MB.',
        uploadFile: 'Subir archivo',
        uploading: 'Subiendo...',
        preparingExport: 'Preparando exportación...',
        allSet: 'Listo.',
        somethingWrong: 'Algo salió mal.',
        uploadComplete: 'Carga completa. Se importaron',
        servicesLabel: 'servicios.',
        uploadFailed: 'La carga falló.',
        exportDownloaded: 'Exportación descargada.',
        exportFailed: 'La exportación falló.',
        uploadMessage: 'Subiendo archivo...',
        exportMessage: 'Preparando exportación...',
        entriesTitle: 'Entradas de servicios',
        entriesSubtitle: 'El nombre del proveedor es obligatorio.',
        addService: 'Agregar servicio',
        searchLabel: 'Buscar servicios',
        searchPlaceholder: 'Buscar por proveedor, categoría o condado',
        serviceLabel: 'Servicio',
        providerName: 'Nombre del proveedor',
        serviceCategory: 'Categoría del servicio',
        serviceTypes: 'Tipos de servicio',
        websiteUrl: 'URL del sitio web',
        phone: 'Teléfono',
        serviceTimes: 'Horarios del servicio',
        accessibility: 'Accesibilidad',
        cost: 'Costo',
        countiesServed: 'Condados atendidos',
        saveSuccess: 'Cambios guardados correctamente.',
        saveError: 'No se pudieron guardar los cambios.',
      },
      websiteTheme: {
        pill: 'Colores del tema',
        title: 'Personalizar colores del tema',
        description: 'Fase 2 - Paso 1: controla fondo global, texto y color primario.',
        autoSaveTitle: 'Auto guardado activo',
        autoSaveDescription: 'Usa Guardar cambios para aplicar las actualizaciones al sitio público.',
        controlsTitle: 'Controles del tema',
        controlsDescription: 'Usa estos selectores para definir la paleta base del sitio.',
        backgroundColor: 'Color de fondo',
        textColor: 'Color de texto',
        primaryColor: 'Color primario',
        resetTheme: 'Restablecer valores',
        defaultsLoaded: 'Tema predeterminado cargado. Haz clic en Guardar cambios para aplicarlo.',
        saveSuccess: 'Tema del sitio guardado correctamente.',
        saveError: 'No se pudo guardar el tema del sitio.',
        invalidHex: 'Introduce colores hex validos (ejemplo: #ffffff).',
        previewTitle: 'Vista previa en vivo',
        previewDescription: 'Esta vista previa usa las mismas variables del sitio público.',
        previewHeading: 'Sección de ejemplo',
        previewBody: 'El estilo del sitio se actualiza de inmediato mientras editas.',
        previewButton: 'Acción primaria',
      },
    },
    home: {
      heroTitle: 'CHOICE Regional Transportation Hub',
      heroDescription1: 'This is the CHOICE Regional Transportation Hub created to help connect community members and providers with transportation resources across the region.',
      heroDescription2: 'This hub was developed in response to regional needs identified through community input and collaboration to improve access to essential care services.',
      heroCta: 'Iniciar mi búsqueda',
      heroImageAlt: 'Conductor solidario brindando transporte',
      partnerLogoAlt: 'Socio',
      supportingPartners: 'Socios de apoyo',
      regionalTitleLine1: 'Socios regionales',
      regionalTitleLine2: 'CHOICE',
      regionalP1:
        'Creemos que las comunidades saludables se construyen sobre relaciones sólidas, donde las personas y los miembros de la comunidad están conectados entre sí y con servicios esenciales.',
      regionalP2:
        'Estamos dedicados a trabajar juntos en soluciones impulsadas por la comunidad para resolver algunos de nuestros desafíos más complejos en la región del centro-oeste del estado de Washington.',
      regionalP3:
        'Este es un centro de recursos de transporte regional de CHOICE. CHOICE trabaja con socios locales para ayudarte a llegar a donde necesitas ir.',
      regionalMapAlt: 'Mapa del estado de Washington que muestra a los socios regionales de CHOICE',
      categories: {
        doctor: 'Viajes para ver a un médico',
        groceries: 'Viajes para comida y compras',
        work: 'Viajes para vivienda y trabajo',
        transit: 'Autobuses y transporte público',
      },
      needHelpTitle: '¿Necesitas ayuda extra?',
      needHelpCta: 'Iniciar mi búsqueda',
      contactTitle: '¿Tienes un recurso sugerido que debamos conocer? ¡Cuéntanos!',
      contactFirstName: 'Nombre',
      contactLastName: 'Apellido',
      contactEmail: 'Correo electrónico',
      contactFeedback: 'Comentarios',
      contactSubmit: 'Enviar',
      contactSubmitting: 'Enviando...',
      contactSuccessTitle: '¡Gracias!',
      contactSuccessBody: 'Tu mensaje se ha enviado correctamente. Nos pondremos en contacto pronto.',
      contactSendAnother: 'Enviar otro mensaje',
      validation: {
        firstNameMin: 'El nombre debe tener al menos 2 caracteres.',
        lastNameMin: 'El apellido debe tener al menos 2 caracteres.',
        emailInvalid: 'Por favor ingresa un correo electrónico válido.',
        feedbackMin: 'Los comentarios deben tener al menos 10 caracteres.',
      },
    },
    directory: {
      title: 'Encuentra Servicios de Transporte',
      filterTitle: 'Filtrar Servicios',
      searchByName: 'Buscar por nombre',
      allCounties: 'Todos los condados',
      searchCounties: 'Buscar condados',
      allServices: 'Tipo de ayuda',
      searchServices: 'Buscar tipo de ayuda',
      allAccessibility: 'Toda la accesibilidad',
      searchAccessibility: 'Buscar accesibilidad',
      startSearch: 'Iniciar mi búsqueda',
      clearAll: 'Limpiar todo',
      noServicesTitle: 'No se encontraron servicios',
      noServicesBody: 'No pudimos encontrar servicios que coincidan con tus filtros actuales. Intenta ajustar tus criterios de búsqueda.',
      clearFilters: 'Limpiar todos los filtros',
      detail: {
        phone: 'Teléfono',
        hours: 'Horario',
        access: 'Acceso',
        cost: 'Costo',
        county: 'Condado',
      },
    },
    partners: {
      searchPlaceholder: 'Buscar socios...',
      showLess: 'Mostrar menos',
      readMore: 'Leer más',
      website: 'Sitio web',
      noResults: 'No se encontraron resultados',
    },
    about: {
      title: 'Acerca de y socios',
      p1: 'The CHOICE Regional Transportation Hub was developed and is maintained by CHOICE Regional Health Network to improve access to transportation for community members across the region. CHOICE created this hub to make it easier for individuals, providers, and care coordinators to find and use transportation services that support access to medical care and essential needs.',
      p2: 'This work builds on regional collaboration through the Great Rivers BH-ASO Transportation Collaborative, where partners identified transportation as a major barrier to accessing care. Community surveys and partner feedback showed that many people were unaware of available transportation resources or unsure how to access them.',
      p3: 'In response, CHOICE Regional Health Network took the lead in creating this centralized hub to bring transportation information together in one place. This hub reflects CHOICE\'s ongoing commitment to improving access to care and strengthening connections between community members and essential services.',
      p4: 'Supporting partners in this effort include Great Rivers BH-ASO, UnitedHealthcare and the Cowlitz-Wahkiakum Council of Governments Mobility Management program, whose collaboration and input helped inform the development of this resource.',
    },
    resources: {
      title: 'Recursos regionales de transporte',
      subtitle: 'Herramientas y socios clave que ayudan a las personas a acceder a atención médica, alimentos y servicios esenciales.',
      cwcogTitle: 'Gestión de movilidad de CWCOG',
      cwcogDesc: 'Herramientas de gestión de movilidad, capacitación para viajar y coordinación regional para conectar a las personas con opciones de transporte.',
      cwcogCta: 'Visitar Gestión de Movilidad de CWCOG',
      grTitle: 'Esfuerzos de transporte de Great Rivers BH-ASO',
      grDesc: 'Coordinación regional enfocada en mejorar el acceso al transporte para salud conductual y otros servicios esenciales.',
      grCta: 'Conocer más sobre Great Rivers BH-ASO',
    },
  },
};

const getNestedValue = (obj, path) => {
  return path.split('.').reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : null), obj);
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return window.localStorage.getItem('choice-language') || 'en';
  });

  useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem('choice-language', language);
  }, [language]);

  const t = useMemo(() => {
    return (key) => {
      const dictionary = translations[language] || translations.en;
      return getNestedValue(dictionary, key) ?? getNestedValue(translations.en, key) ?? key;
    };
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
};
